#!/usr/bin/env bash
# Bring up the dev stack: Splunk (this repo's app mounted live) + ir.mlab.sh, secrets wired. Safe to re-run.
set -euo pipefail
cd "$(dirname "$0")/.."

IR=http://localhost:8080
SPLUNK=https://localhost:8089
AUTH=admin:changeme123
GEN=dev/.generated
mkdir -p "$GEN"
say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
envval() { grep -E "^$1=" .env | tail -1 | cut -d= -f2- || true; }
sp() { curl -sk -u "$AUTH" "$@"; }  # Splunk REST

say "Disk"
# Keep 5 GB free on the host no matter what; the images take ~9 GB the first time.
free_gb=$(df -g . | awk 'NR==2 {print $4}')
need=6
docker image inspect "splunk/splunk:${SPLUNK_VERSION:-10.4.3}" >/dev/null 2>&1 || need=12
docker image inspect ghcr.io/mlab-sh/ir.mlab.sh:latest >/dev/null 2>&1 || need=$((need+4))
echo "${free_gb} GB free, ${need} GB needed (5 GB kept as margin)"
[ "$free_gb" -ge "$need" ] || { echo "not enough disk, aborting"; exit 1; }

say "Secrets"
[ -n "$(envval MLAB_IR_LI)" ] || { echo "MLAB_IR_LI (ir.mlab.sh licence) missing from .env"; exit 1; }
if [ -z "$(envval INTERNAL_SECRET)" ]; then
  printf '\n# generated by dev/setup.sh (ir.mlab.sh app <-> executor)\nINTERNAL_SECRET=%s\n' "$(openssl rand -hex 32)" >> .env
  echo "INTERNAL_SECRET added to .env"
fi

say "Stack"
docker compose up -d

say "ir.mlab.sh"
printf 'waiting for %s ' "$IR"
until curl -s -o /dev/null "$IR/"; do printf .; sleep 3; done; echo " up"
if [ ! -s "$GEN/ir_token" ]; then
  jar="$GEN/ir_cookies"
  curl -sf -c "$jar" -H 'Content-Type: application/json' \
    -d '{"email":"admin@localhost","password":"adminadmin"}' "$IR/api/v1/auth/login" > /dev/null
  curl -sf -b "$jar" -H 'Content-Type: application/json' \
    -d '{"note":"splunk dev stack","kind":"app"}' "$IR/api/v1/user/apikey/create" \
    | python3 -c 'import json,sys,re; print(re.search(r"mlab_app_[0-9A-Za-z]+", json.dumps(json.load(sys.stdin))).group(0))' \
    > "$GEN/ir_token"
  echo "app token created ($GEN/ir_token)"
else
  echo "app token already created"
fi

say "mlab.sh API key"
if [ -n "$(envval MLAB_API_KEY)" ]; then
  # a bad key is not rejected by mlab.sh, it silently falls back to anonymous quotas: check it
  curl -s -H "Authorization: token $(envval MLAB_API_KEY)" https://mlab.sh/api/v1/ | grep -q '"auth": *"api_key"' \
    && echo "valid" || { echo "MLAB_API_KEY in .env is not accepted by mlab.sh"; exit 1; }
else
  echo "none in .env: anonymous lookups (IP quota 5/day)"
fi

say "Splunk"
printf 'waiting for splunkd (first start under emulation takes a few minutes) '
until [ "$(sp -o /dev/null -w '%{http_code}' "$SPLUNK/services/server/info")" = 200 ]; do printf .; sleep 5; done; echo " up"
# storage/passwords: create, or update if it exists
secret() {
  sp -o /dev/null -X DELETE "$SPLUNK/servicesNS/nobody/mlab/storage/passwords/mlab:$1:"
  sp -f -o /dev/null "$SPLUNK/servicesNS/nobody/mlab/storage/passwords" -d realm=mlab -d "name=$1" --data-urlencode "password=$2" \
    && echo "storage/passwords mlab:$1 set" || { echo "could not store $1"; exit 1; }
}
secret ir_token "$(cat "$GEN/ir_token")"
[ -n "$(envval MLAB_API_KEY)" ] && secret api_key "$(envval MLAB_API_KEY)"
# ir.mlab.sh as seen from the Splunk container
sp -f -o /dev/null "$SPLUNK/servicesNS/nobody/mlab/configs/conf-alert_actions/mlab_ir" -d param.base_url=http://ir-app:8080 \
  && echo "mlab_ir base_url = http://ir-app:8080 (mlab/local/alert_actions.conf, git-ignored)"

cat <<EOF

Stack is up:
  Splunk      http://localhost:8000   admin / changeme123
  ir.mlab.sh  $IR   admin@localhost / adminadmin
Run the end-to-end checks:  dev/e2e.sh
EOF
